import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from "@/components/navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Evento",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      
      <body className={inter.className}>
  
          
      <ClerkProvider>
          <Navbar />
          {children}
    </ClerkProvider>
        </body>
    </html>

  );
}
